### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-workstation-docs#10]
An FAQ should be visible on the homepage in right/wide/main column, when the docs load. 

If RTD supports an Accordion interaction pattern, it feels somewhat urgent that the FAQ exist as a single-page artifact w/in RTD, packed w/ accordion or drawer containers that may each be linked-to, externally (like, I'd love it if the Connection error could link-out to the connectivity thing, here, vs forcing the user to think "Hmm, I should open the docs and find this FAQ!"). 
  - When each bucket is opened, any already-open bucket should close—and upon loading, all buckets should load, closed. 
  - [This](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/reference-third-party-css-styles) and [that](https://docs.telerik.com/devtools/xamarin/controls/accordion/accordion-overview) and [this](http://crossfitpfb.com/got-questions/) are examples of Accordion (or “Drawer”) interaction pattern.

## Qubes 
Q: Why are there multiple updaters?
A: (outline)
- Intro sentence to qualify what updaters there are. Maybe 3, no more than 3. One sentence to explain why they need to be separate; this may be common-knowledge stuff to us about how FOSS projects operate, but it needs to exist.
- Qubes Updater
- Preflight Updater
- Another one?

Q: Why can’t I cut-and-paste?
Q: Why can’t I save or print from the Viewer VM apps?
Q: I want to create and save a document or spreadsheet for logging or general notes, on my Workstation Laptop. How can I do that?

## SecureDrop 
Q: Why can’t I cut-and-paste?
A: (blathering on how to use Qubes cut-and-paste)

Q: My connection dropped
A: (yeah, sorry—we know this sucks) (How to troubleshoot)

Q: Downloads and updates take too long
A: Speak to this a bit.

**Comment by ninavizz** [comment]
My primary concern with the user documentation, is forcing consumer-product trained users into a mental model of having to reverse-engineer their front-of-mind question, to fit within a long-form framing of “Here’s how it should work.” As nerds, this is ok for us because we are used to operating like that. Consumer-type users are not accustomed to this, and being forced into that can cause frustration and be discouraging.

**Comment by rocodes** [comment]
@olivemartini has indicated interest in helping with some of these Qubes-related Q&A - we will coordinate

**Comment by olivemartini** [comment]
Yup, this is right up my alley. I can take a deep look into this tomorrow.

**Comment by eloquence** [comment]
This was done via #13 and subsequent PRs; additional improvements can be tracked separately.
