### ISSUE TITLE
Docs update for 4.1: screenshots

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#105]
The GUI has changed in some significant and some more subtle was on 4.1 (e.g., very significant changes to VM iconography). We should do a full screenshots refresh around the time of the grand migration.

**Comment by cfm** [comment]
I've reviewed the remaining pre‒Qubes 4.1 screenshots.  My instinct is that we'd be best served by doing further updates to reflect the SecureDrop Client's current GUI after its next release.  Please feel free reopen this ticket, @eloquence or @nathandyer, if you feel these updates deserve attention sooner than that!
