### ISSUE TITLE
Disable ads

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#20]
https://workstation.securedrop.org/ currently builds with ads; we should disable these for the pilot. This may require another $5/month subscription per https://github.com/freedomofpress/securedrop/issues/4065 ; if so, I would still be in favor of disabling since this is a flagship project for us.

**Comment by conorsch** [comment]
Done. Did indeed raise the subscription +$5/month, well worth it for such a convenient service. Both SDO core docs and SDW docs are now showing zero ads for me. @eloquence once you confirm, OK to close!

**Comment by eloquence** [comment]
Confirmed, thank you! <3
