### ISSUE TITLE
Document that Submission Keys with Passphrases are not supported by SecureDrop Workstation

### ISSUE THREAD

**Issue by nathandyer** [freedomofpress/securedrop-workstation-docs#281]
Although we recommend against setting a passphrase for the submission private key when setting up a SecureDrop Server, it is possible that one has been set by a user anyway. While this works for the classic SecureDrop Tails system on the Secure Viewing Station, trying to import a Submission Key with a passphrase set will result in an error when running `sdw-admin --validate`, and cannot be used by the Client.

We should add a note to the documentation explaining that Submission Keys with Passphrases are not supported.

Additionally, I recommend that we suggest that users reach out to support in the event that they have a submission key with a passphrase set so we can assist with exporting a version without a passphrase set (I feel these instructions are specific/obscure enough to not merit being added to the public documentation, but if others feel differently I'd be open to including them in the docs as well).

**Comment by zenmonkeykstop** [comment]
Is this a dupe of #95 ?

**Comment by nathandyer** [comment]
Ah yup - will close this one and add comments into the existing thread
