### ISSUE TITLE
Test T490 and update hardware recommendations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#37]
The ThinkPad T480 is [no longer available](https://www.lenovo.com/us/en/laptops/thinkpad/thinkpad-t-series/ThinkPad-T480/p/22TP2TT4800) from Lenovo, which makes it unsuitable as an official hardware recommendation. The next product in the series is, unsurprisingly, the T490. We should do a full prod setup on that hardware (including BIOS changes) to ensure that it works, and document any needed workarounds.

**Comment by conorsch** [comment]
In the minimal testing I've done so far on the T490, ethernet support was a problem out of the box. After disabling ethernet in the BIOS, Qubes worked just fine. Haven't tinkered with it to try to restore functionality.

**Comment by gonzalo-bulnes** [comment]
Light touch point, I followed the steps described in [the T490 Workstation docs](https://workstation.securedrop.org/en/stable/admin/hardware.html#lenovo-thinkpad-t490-with-8th-generation-intel-core-processor) today and they're accurate / just what's needed. :+1:
