### ISSUE TITLE
Document playbook run requirement for old installs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#39]
During a recent install, we encountered ETag errors from the API, which indicates that the Ansible playbook that applied a relevant change had not been run. The issue was resolved by running an up-to-date Ansible playbook.

We should document any playbook run requirements needed for successful SecureDrop Workstation use with a long-running server.

**Comment by redshiftzero** [comment]
Orgs need to have had a playbook run on 0.13.0 or later to include [these changes](https://github.com/freedomofpress/securedrop/pull/4023) - e.g. orgs that upgraded to Xenial (running the playbooks) right after 0.12.0 was released will need to run the playbooks once again.
