### ISSUE TITLE
Determine branching/release strategy for this repo

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#41]
As noted on on https://github.com/freedomofpress/securedrop-workstation-docs/pull/35#issuecomment-624372222 we should decide on how we want to merge/release docs changes, now that we have limited production usage of SecureDrop Workstation. (There's potential for confusion and errors if we deploy docs updates for changes that have not landed in a production release yet.)

For example, we could set up a `develop` branch similar to SecureDrop Core, and use that as a staging ground for _all_ changes -- with some trickling to `master` immediately, and others held back until the applicable release is live.

Let's aim to build consensus on this ticket for the preferred approach and then document and implement it.

**Comment by zenmonkeykstop** [comment]
Drawing on lessons from docs.securedrop.org, maybe 
- have a `develop` branch that maps to latest as suggested, 
- create release tags for versions of the docs considered stable, which RTD will then pick up on, and
- only have `latest` and `stable` active in RTD?

**Comment by eloquence** [comment]
Can you expand on your proposal a bit, Kev? If I'm imagining the use of a tag in a single `develop` branch that would identify the stable release, it's not clear to me how we would solve for this case:

```
2020-05-07 52f8ea8f - urgent commit for prod  <-- tagging this would pull in previous commits for dev
2020-05-05 d402454a - commit for dev
2020-05-03 703bc9eb - commit for dev
```

For example, it seems like if we merged the copy & paste change in #33, we'd be forced to back out that change to tag an urgent prod release. Or am I misunderstanding something?

**Comment by eloquence** [comment]
I'm OK with trying a tag-based approach for now; the occasional case of having to back out changes may outweigh the cost of having to perpetually maintain two branches here.

**Comment by eloquence** [comment]
There's now a `stable` tag, and the docs are set to load it by default. We'll have to advance that tag whenever we make changes that are applicable to the current production release. `latest` should continue to build from `master`. Leaving this issue open until we've had at least a couple of days to test drive this setup.

I use annotated tags signed with my FPF key for the current `stable` tag.
