### ISSUE TITLE
Network troubleshooting docs specify using `curl` in sd-proxy, but it is not installed

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#56]
Our docs here:

https://workstation.securedrop.org/en/stable/admin/troubleshooting_connection.html#step-4-verify-that-required-vms-have-connectivity

specify the use of `curl` to test connectivity, but it is not installed in `sd-proxy`. We should either install it in the template, or recommend a different command (`wget` is installed.).

**Comment by conorsch** [comment]
Using `wget` sounds great, since it's a simple fix. Confirmed that `wget` is indeed installed in `sd-proxy`, as @eloquence reports, and it's also available by default in `sd-whonix`.
