### ISSUE TITLE
Add docs for read/unread, updated screenshots w/ new source list layout

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-docs#68]
SecureDrop Client 0.4.0 ships initial support for seen/unseen at the source level (sources with submissions unseen by any journalist user are bolded). It also changes the layout of the source list to be more compact. We should document the seen/unseen feature, and update our screenshots.

**Comment by eloquence** [comment]
Probably best done alongside other screenshot updates, e.g., #61, and updated screenshots in our training slide deck.

**Comment by eloquence** [comment]
Not exhaustive yet, but here's a screenshot that shows just seen/unseen (bolded sources vs. unbolded ones):
![read-unread-1](https://user-images.githubusercontent.com/213636/109738549-dd116d00-7b7c-11eb-85be-29e3931b6f14.png)

And here's one with a document and a conversation selected.
![client-with-documents](https://user-images.githubusercontent.com/213636/109738482-b9e6bd80-7b7c-11eb-99e7-9aaa251806ef.png)

**Comment by eloquence** [comment]
Updater flow for good measure (since the Whonix icons have changed relative to what's in the docs):

![updater1](https://user-images.githubusercontent.com/213636/109738757-3c6f7d00-7b7d-11eb-8659-31279f07951c.png)
![updater2](https://user-images.githubusercontent.com/213636/109738756-3c6f7d00-7b7d-11eb-8e49-90e5e2ba8365.png)
![updater3](https://user-images.githubusercontent.com/213636/109738753-3bd6e680-7b7d-11eb-9d0c-91994d131be6.png)
![updater4](https://user-images.githubusercontent.com/213636/109738752-3b3e5000-7b7d-11eb-825a-50d816ea18cb.png)

**Comment by ninavizz** [comment]
Lookit those swell new Whonix icons!

**Comment by eloquence** [comment]
See also https://github.com/freedomofpress/securedrop-workstation/issues/719 for other needed screenshot updates.

**Comment by eloquence** [comment]
OK, I've taken a whole new set of screenshots. This time I renamed the system user account to `nbly` first, as well. I'll start putting these into the docs in the next couple of days and then will fill in any remaining gaps.

![newsc026](https://user-images.githubusercontent.com/213636/150070773-d90911b9-202d-45bb-b790-91060b75432b.png)
![newsc025](https://user-images.githubusercontent.com/213636/150070775-1aed43d6-e7ef-4569-a3aa-57321e193851.png)
![newsc024](https://user-images.githubusercontent.com/213636/150070778-40e19ef1-48f9-49fd-9c48-f9a4467220a8.png)
![newsc023](https://user-images.githubusercontent.com/213636/150070779-9489ba9b-a429-4c38-bdde-8369ef858416.png)
![newsc022](https://user-images.githubusercontent.com/213636/150070781-1b2253c7-13e2-4ee5-bf6d-3c01d4d7b7b4.png)
![newsc021](https://user-images.githubusercontent.com/213636/150070782-a52075d6-a331-4bc6-82c7-4db315c2bd23.png)
![newsc020](https://user-images.githubusercontent.com/213636/150070783-9ba2b85f-951f-4e85-9fa3-5a421c817d0f.png)
![newsc019](https://user-images.githubusercontent.com/213636/150070784-705734fe-a461-4571-b103-3fcf89ab7e19.png)
![newsc018](https://user-images.githubusercontent.com/213636/150070788-35fa4a66-4aa9-4571-ae8b-6b9f246ef152.png)
![newsc017](https://user-images.githubusercontent.com/213636/150070789-f6526618-c3b1-4216-bc6d-c1972468d180.png)
![newsc016](https://user-images.githubusercontent.com/213636/150070792-9d781e2a-26dc-43c4-a8d4-52a7b5a1a563.png)
![newsc015](https://user-images.githubusercontent.com/213636/150070794-ab781122-8a1a-411a-95e5-921469215c5a.png)
![newsc014](https://user-images.githubusercontent.com/213636/150070796-cfa72aeb-f510-4311-8f25-51ccdc4b608c.png)
![newsc013](https://user-images.githubusercontent.com/213636/150070797-3830f031-6e4d-4051-a787-e19b48dc743d.png)
![newsc012](https://user-images.githubusercontent.com/213636/150070800-8e772edc-6897-4fe0-80e4-85f5e2cff8ce.png)
![newsc011](https://user-images.githubusercontent.com/213636/150070802-3d5e7f40-8112-45fe-99f0-8c49896a4331.png)
![newsc010](https://user-images.githubusercontent.com/213636/150070803-26ac70bb-25b1-444c-bf8f-b5b70d81ad75.png)
![newsc009](https://user-images.githubusercontent.com/213636/150070805-d8a5e53c-8faa-4b8e-9c42-0f02f3fac7f6.png)
![newsc008](https://user-images.githubusercontent.com/213636/150070806-1cad590c-ce23-43ee-86a1-76ed99ffee5b.png)
![newsc007](https://user-images.githubusercontent.com/213636/150070807-caa36ed0-7444-4d8f-b505-1f811163a04b.png)
![newsc006](https://user-images.githubusercontent.com/213636/150070809-01cd0343-6591-4e5d-b0b7-736e0e72be3a.png)
![newsc005](https://user-images.githubusercontent.com/213636/150070811-d18e1c37-15c4-4f21-81b6-b9c8576fdbab.png)
![newsc004](https://user-images.githubusercontent.com/213636/150070813-59746739-5c89-4ac7-bf64-70f767218a99.png)
![newsc003](https://user-images.githubusercontent.com/213636/150070816-b82db141-da09-42a3-a5fe-11b2c175939d.png)
![newsc002](https://user-images.githubusercontent.com/213636/150070820-65d0be30-f05b-43c2-bb85-e3fcd3a2a640.png)
![newsc001](https://user-images.githubusercontent.com/213636/150070822-211b424a-dd72-4421-8103-b153fe31bf01.png)

![newsc031](https://user-images.githubusercontent.com/213636/150070761-afbe0ec9-d0f4-4105-a88d-fdd38cd0b214.png)
![newsc030](https://user-images.githubusercontent.com/213636/150070763-64187dce-277e-4d46-bd21-efd1b458a5a1.png)
![newsc029](https://user-images.githubusercontent.com/213636/150070766-c5442f01-ddfd-4499-9fac-9292e0621de3.png)
![newsc028](https://user-images.githubusercontent.com/213636/150070767-19f1cf34-6c43-4d08-8ede-6e1b5f0cc465.png)
![newsc027](https://user-images.githubusercontent.com/213636/150070770-a40cf5f6-1f21-47eb-a94d-5802d7a880d9.png)
