### ISSUE TITLE
Add docs on features and limitations of SDW

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-workstation-docs#92]
# Description

It might be confusing to journalists what they can and cannot do on the SDW without a comprehensive list of features and current limitations, e.g. which printers we currently support (see `securedrop-export`). Another useful docs improvement would be to highlight which features will require the use of the web interface versus the desktop interface.

**Comment by eloquence** [comment]
We do have such a chapter, currently in the admin guide:
https://workstation.securedrop.org/en/stable/admin/known_issues.html

However, it could certainly be expanded.

**Comment by nathandyer** [comment]
We can probably close this thanks to the recent round of PRs that have been added:
* https://github.com/freedomofpress/securedrop-workstation-docs/pull/232
* https://github.com/freedomofpress/securedrop-workstation-docs/pull/245
* https://github.com/freedomofpress/securedrop-workstation-docs/pull/236
